/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ope' at '16/03/07 10:50' with Gradle 2.11
 *
 * @author ope, @date 16/03/07 10:50
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
