/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ope' at '16/02/11 10:37' with Gradle 2.11
 *
 * @author ope, @date 16/02/11 10:37
 */

import org.yaml.snakeyaml.* ;
import java.io.* ;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

	public String load( String file ) {
		Yaml yaml = new Yaml() ;
		Object a = yaml.load( new InputStreamReader(
			this.getClass().getClassLoader().getResourceAsStream( file )
		) ) ;
		return a.getClass().toString() ;
	}
}
