/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ope' at '6/28/16 4:15 PM' with Gradle 2.14
 *
 * @author ope, @date 6/28/16 4:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
