import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.* ;
import java.util.* ;
import java.math.BigDecimal;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ope' at '6/28/16 4:15 PM' with Gradle 2.14
 *
 * @author ope, @date 6/28/16 4:15 PM
 */
public class LibraryTest {

	public static class RefClass {
		public void arr( int[] x, int y ) {
		}
	}


    @Test public void testSomeLibraryMethod() throws Exception {

		new RefClass().arr( null, 1 ) ;

	Method method = RefClass.class.getMethod( "arr", int[].class, int.class ) ;

	ArrayList pa = new ArrayList() ;
//	method.invoke( new RefClass(), pa, 2 ) ;

    }

	@Test public void testCollections() throws Exception {

		ArrayList o = new ArrayList() ;

		assertEquals( o.size() , 0 ) ; 

		o.add( 1 ) ;
		assertEquals( o.size() , 1 ) ; 
		o.addAll( new ArrayList(){{ add( new int[]{ 1 , 2 } ) ; }}  ) ;
		assertEquals( o.size() , 2 ) ; 

		o.addAll( new ArrayList(){{ add( new BigDecimal[]{ BigDecimal.valueOf(1.0), BigDecimal.valueOf(2.0) } ) ; }}  ) ;
		assertEquals( o.size() , 3 ) ; 

		o.addAll( new BigDecimal[]{ BigDecimal.valueOf(1.0), BigDecimal.valueOf(2.0) } ) ;
		assertEquals( o.size() , 4 ) ; 
		
	}
}
