/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ope' at '16/02/24 20:02' with Gradle 2.11
 *
 * @author ope, @date 16/02/24 20:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

	public void charSet() {
	}
}
