/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ope' at '16/05/30 13:39' with Gradle 2.11
 *
 * @author ope, @date 16/05/30 13:39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
