import org.junit.Test;
import static org.assertj.core.api.Assertions.*;
import org.apache.commons.lang3.* ;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ope' at '16/02/24 20:02' with Gradle 2.11
 *
 * @author ope, @date 16/02/24 20:02
 */
public class LibraryTest {
	@Test
	public void testCharSet() {
		CharSet set = CharSet.getInstance( "abz" ) ;
		assertThat( set.contains( 'a' ) ).isEqualTo( true ) ;
	}
}
