/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ope' at '11/15/16 11:16 AM' with Gradle 2.14
 *
 * @author ope, @date 11/15/16 11:16 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
