import static org.assertj.core.api.Assertions.*;
import org.junit.Test;
import mockit.*;
import java.time.* ;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ope' at '16/03/08 14:57' with Gradle 2.11
 *
 * @author ope, @date 16/03/08 14:57
 */
public class LibraryTest {

    @Test
	public void testSomeLibraryMethod( ) {

		final LocalDateTime n =  LocalDateTime.of(1900,1,1,1,1) ;

		new NonStrictExpectations(n) {{
			n.now(); result = n ;
			n.getDayOfMonth(); result = 10 ;
		}} ;
		assertThat( LocalDateTime.now().getDayOfMonth() ).isEqualTo(10) ;
		assertThat( LocalDateTime.now().getYear() ).isEqualTo(1900) ;
    }

    @Test
	public void testSomeLibraryMethodZZ() {
		assertThat( LocalDateTime.now().getYear() ).isEqualTo(2016) ;
	}

}
