import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ope' at '16/03/07 10:50' with Gradle 2.11
 *
 * @author ope, @date 16/03/07 10:50
 */
public class LibraryTest {

	public static void varArg( Object... param ) {
		if( param == null ) {
			System.out.println( "null" ) ;
		}
		else {
			System.out.println( param.length ) ;
		}
	}


	@Test
	public void testABC() {
System.out.println ( "" );
System.out.println ( "0>" );
		varArg( 1,2,3 ) ;
System.out.println ( "1>" );
		varArg( 1,2,3 ) ;
System.out.println ( "2>" );
		varArg( 1,null,3 ) ;
System.out.println ( "3>" );
		varArg( null,2,3 ) ;
System.out.println ( "4>" );
		varArg( 1,2,null ) ;
System.out.println ( "5>" );
	}
}
