/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ope' at '11/9/17 6:43 PM' with Gradle 2.14
 *
 * @author ope, @date 11/9/17 6:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
